name: Build LoveCompat APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          unzip -q LoveCompat-Android-v1.0-FIXED3.zip -d project
          cd project/compatibility_app

          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

          gradle --version
          gradle assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: LoveCompat-APK
          path: project/compatibility_app/app/build/outputs/apk/debug/*.apk
